# Generated by Django 5.2.5 on 2026-02-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting_system', '0002_add_undertone_and_expand_skin_tone'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodyscan',
            name='arm_length',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bodyscan',
            name='body_shape',
            field=models.CharField(blank=True, choices=[('hourglass', 'Hourglass'), ('rectangle', 'Rectangle'), ('triangle', 'Triangle (Pear)'), ('inverted_triangle', 'Inverted Triangle (Athletic)'), ('oval', 'Oval (Apple)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bodyscan',
            name='confidence_score',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='bodyscan',
            name='frame_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bodyscan',
            name='hip',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bodyscan',
            name='inseam',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bodyscan',
            name='torso_length',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bodyscan',
            name='chest',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='bodyscan',
            name='height',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='bodyscan',
            name='shoulder_width',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='bodyscan',
            name='waist',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
