# Generated by Django 4.2.7 on 2026-02-24 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitting_system', '0004_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
