# Generated by Django 5.2.5 on 2026-02-25 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitting_system', '0004_bodyscan_error_message_bodyscan_is_fallback'),
        ('fitting_system', '0005_remove_product_image_url'),
    ]

    operations = [
    ]
